############### SENSORS ###############
metrics:
    CpuLoad:
        /dev/shm/CpuLoad.key
    CpuFreq:
        /dev/shm/CpuFreq.key
    VirtMemTot:
        /dev/shm/VirtMemTot.key
    VirtMemAvail:
        /dev/shm/VirtMemAvail.key
    DiskUsage:
        /dev/shm/DiskUsage.key
sensors:
    PositionV13:
        /dev/shm/PositionV13.key
    PositionW13:
        /dev/shm/PositionW13.key
    PositionV24:
        /dev/shm/PositionV24.key
    PositionW24:
        /dev/shm/PositionW24.key
    PositionV57:
        /dev/shm/PositionV57.key
    PositionW57:
        /dev/shm/PositionW57.key
    Positionz1:
        /dev/shm/Positionz1.key
    PositionZ12:
        /dev/shm/PositionZ12.key
    CommandeV1:
        /dev/shm/CommandeV1.key
    CommandeV3:
        /dev/shm/CommandeV3.key
    CommandeV2:
        /dev/shm/CommandeV2.key
    CommandeV4:
        /dev/shm/CommandeV4.key
    CommandeV5:
        /dev/shm/CommandeV5.key
    CommandeV7:
        /dev/shm/CommandeV7.key
    CommandeW1:
        /dev/shm/CommandeW1.key
    CommandeW3:
        /dev/shm/CommandeW3.key
    CommandeW2:
        /dev/shm/CommandeW2.key
    CommandeW4:
        /dev/shm/CommandeW4.key
    CommandeW5:
        /dev/shm/CommandeW5.key
    CommandeW7:
        /dev/shm/CommandeW7.key
    Commandez1:
        /dev/shm/Commandez1.key
    CommandeZ2:
        /dev/shm/CommandeZ2.key
    TDCBit:
        /dev/shm/TDCBit.key
    CurrentV1:
        /dev/shm/CurrentV1.key
    CurrentV3:
        /dev/shm/CurrentV3.key
    CurrentV2:
        /dev/shm/CurrentV2.key
    CurrentV4:
        /dev/shm/CurrentV4.key
    CurrentV5:
        /dev/shm/CurrentV5.key
    CurrentV7:
        /dev/shm/CurrentV7.key
    CurrentW1:
        /dev/shm/CurrentW1.key
    CurrentW3:
        /dev/shm/CurrentW3.key
    CurrentW2:
        /dev/shm/CurrentW2.key
    CurrentW4:
        /dev/shm/CurrentW4.key
    CurrentW5:
        /dev/shm/CurrentW5.key
    CurrentW7:
        /dev/shm/CurrentW7.key
    CurrentZ1:
        /dev/shm/CurrentZ1.key
    CurrentZ2:
        /dev/shm/CurrentZ2.key
    CurrentZ3:
        /dev/shm/CurrentZ3.key
    CurrentZ4:
        /dev/shm/CurrentZ4.key
    Rotation_Frequency_A:
        /dev/shm/Rotation_Frequency_A.key
    Rotation_Frequency_B:
        /dev/shm/Rotation_Frequency_B.key
    SPV_speed_A:
        /dev/shm/SPV_speed_A.key
    SPV_speed_B:
        /dev/shm/SPV_speed_B.key
    UnbalanceA13:
        /dev/shm/UnbalanceA13.key
    UnbalanceB13:
        /dev/shm/UnbalanceB13.key
    UnbalanceA24:
        /dev/shm/UnbalanceA24.key
    UnbalanceB24:
        /dev/shm/UnbalanceB24.key
    UnbalanceA57:
        /dev/shm/UnbalanceA57.key
    UnbalanceB57:
        /dev/shm/UnbalanceB57.key
    AxialHarmonic1A:
        /dev/shm/AxialHarmonic1A.key
    AxialHarmonic1B:
        /dev/shm/AxialHarmonic1B.key
    MachineTemp_1_A:
        /dev/shm/MachineTemp_1_A.key
    MachineTemp_2_A:
        /dev/shm/MachineTemp_2_A.key
    MachineTemp_3_A:
        /dev/shm/MachineTemp_3_A.key
    MachineTemp_4_A:
        /dev/shm/MachineTemp_4_A.key
    MachineTemp_5_A:
        /dev/shm/MachineTemp_5_A.key
    MachineTemp_6_A:
        /dev/shm/MachineTemp_6_A.key
    MachineTemp_7_A:
        /dev/shm/MachineTemp_7_A.key
    MachineTemp_8_A:
        /dev/shm/MachineTemp_8_A.key
    MachineTemp_1_B:
        /dev/shm/MachineTemp_1_B.key
    MachineTemp_2_B:
        /dev/shm/MachineTemp_2_B.key
    MachineTemp_3_B:
        /dev/shm/MachineTemp_3_B.key
    MachineTemp_4_B:
        /dev/shm/MachineTemp_4_B.key
    MachineTemp_5_B:
        /dev/shm/MachineTemp_5_B.key
    MachineTemp_6_B:
        /dev/shm/MachineTemp_6_B.key
    MachineTemp_7_B:
        /dev/shm/MachineTemp_7_B.key
    MachineTemp_8_B:
        /dev/shm/MachineTemp_8_B.key
    coilTempV1:
        /dev/shm/coilTempV1.key
    coilTempV3:
        /dev/shm/coilTempV3.key
    coilTempv2:
        /dev/shm/coilTempv2.key
    coilTempv4:
        /dev/shm/coilTempv4.key
    coilTempv5:
        /dev/shm/coilTempv5.key
    coilTempV7:
        /dev/shm/coilTempV7.key
    coilTempw1:
        /dev/shm/coilTempw1.key
    coilTempW3:
        /dev/shm/coilTempW3.key
    coilTempW2:
        /dev/shm/coilTempW2.key
    coilTempW4:
        /dev/shm/coilTempW4.key
    coilTempW5:
        /dev/shm/coilTempW5.key
    coilTempW7:
        /dev/shm/coilTempW7.key
    coilTempZI:
        /dev/shm/coilTempZI.key
    coilTempZ2:
        /dev/shm/coilTempZ2.key
    coilTempz3:
        /dev/shm/coilTempz3.key
    coilTempZ4:
        /dev/shm/coilTempZ4.key
    peakPositionv13:
        /dev/shm/peakPositionv13.key
    peakPositionW13:
        /dev/shm/peakPositionW13.key
    peakPositionV24:
        /dev/shm/peakPositionV24.key
    peakPositionW24:
        /dev/shm/peakPositionW24.key
    peakPositionV57:
        /dev/shm/peakPositionV57.key
    peakPositionW57:
        /dev/shm/peakPositionW57.key
    peakPositionz1:
        /dev/shm/peakPositionz1.key
    peakPosition22:
        /dev/shm/peakPosition22.key
    PeakElongation_Rotor_SPV:
        /dev/shm/PeakElongation_Rotor_SPV.key
    VDCMains:
        /dev/shm/VDCMains.key
    VDCPA_V13:
        /dev/shm/VDCPA_V13.key
    VDCPA_W13:
        /dev/shm/VDCPA_W13.key
    VDCPA_V24:
        /dev/shm/VDCPA_V24.key
    VDCPA_W24:
        /dev/shm/VDCPA_W24.key
    VDCPA_V57:
        /dev/shm/VDCPA_V57.key
    VDCPA_W57:
        /dev/shm/VDCPA_W57.key
    VDCPA_Z12:
        /dev/shm/VDCPA_Z12.key
    VDCPA_234:
        /dev/shm/VDCPA_234.key
    AmplifierTempv13:
        /dev/shm/AmplifierTempv13.key
    AmplifierTempW13:
        /dev/shm/AmplifierTempW13.key
    AmplifierTempv24:
        /dev/shm/AmplifierTempv24.key
    AmplifierTempW24:
        /dev/shm/AmplifierTempW24.key
    AmplifierTempV57:
        /dev/shm/AmplifierTempV57.key
    AmplifierTempW57:
        /dev/shm/AmplifierTempW57.key
    AmplifierTempz12:
        /dev/shm/AmplifierTempz12.key
    AmplifierTempz34:
        /dev/shm/AmplifierTempz34.key
    ISO_Bear_A:
        /dev/shm/ISO_Bear_A.key
    ISO_Det_A:
        /dev/shm/ISO_Det_A.key
    ISO_Bear_B:
        /dev/shm/ISO_Bear_B.key
    ISO_Det_B:
        /dev/shm/ISO_Det_B.key
    RadialHarmonicN2A13:
        /dev/shm/RadialHarmonicN2A13.key
    RadialHarmonicN2B13:
        /dev/shm/RadialHarmonicN2B13.key
    RadialHarmonicN2A24:
        /dev/shm/RadialHarmonicN2A24.key
    RadialHarmonicN2824:
        /dev/shm/RadialHarmonicN2824.key
    RadialHarmonicN2A57:
        /dev/shm/RadialHarmonicN2A57.key
    RadialHarmonicN2B57:
        /dev/shm/RadialHarmonicN2B57.key
    AxialHarmonicN2A:
        /dev/shm/AxialHarmonicN2A.key
    AxialHarmonicN2B:
        /dev/shm/AxialHarmonicN2B.key
