attrs:
        Figure:
                background_fill_color: "#FFFFFF"
                border_fill_color: "#FFFFFF"
                outline_line_color: "#0072BC"

        Axis:
                axis_line_color: "#0072BC"
                axis_label_text_color: "#0072BC"
                major_label_text_color: "#0072BC"
                major_tick_line_color: "#0072BC"
                minor_tick_line_color: "#0072BC"

        Grid:
                grid_line_dash: [6, 4]
                grid_line_alpha: .3

        Title:
                text_color: "#0072BC"



