############# PYTHON DOCUMENTATION ##########

SPHINXOPTS    ?=
SPHINXBUILD   ?= sphinx-build
SOURCEDIR     = docs/python/source
BUILDDIR      = docs/python/build

.PHONY: Makefile

all:
	"Preparing project..."

docs:	Makefile
	@$(SPHINXBUILD) -b html "$(SOURCEDIR)" "$(BUILDDIR)"

